import { useState } from 'react';
const formatDate=(value)=>new Date(value).toLocaleString();
const LABELS={1:'Very dissatisfied',2:'Dissatisfied',3:'Neutral',4:'Satisfied',5:'Very satisfied'};
export default function PortalTicket({initialTicket,initialCsat,token}){
  const [ticket,setTicket]=useState(initialTicket);const [csat,setCsat]=useState(initialCsat);const [reply,setReply]=useState('');const [rating,setRating]=useState(initialCsat?.rating||0);const [comment,setComment]=useState(initialCsat?.comment||'');const [error,setError]=useState('');const [csatError,setCsatError]=useState('');
  const refresh=async()=>{const [ticketResponse,csatResponse]=await Promise.all([fetch(`/api/portal/${token}`),fetch(`/api/portal/${token}/csat`)]);if(ticketResponse.ok)setTicket((await ticketResponse.json()).ticket);if(csatResponse.ok){const next=(await csatResponse.json()).csat;setCsat(next);setRating(next.rating||0);setComment(next.comment||'');}};
  const send=async()=>{if(!reply.trim())return;const response=await fetch(`/api/portal/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:reply})});const payload=await response.json().catch(()=>({}));if(!response.ok)return setError(payload.message||'Unable to send reply.');setReply('');setError('');setTicket(payload.ticket);if(!['resolved','closed'].includes(payload.ticket.status))setCsat({eligible:false,submitted:false});};
  const submitCsat=async()=>{if(!rating)return;setCsatError('');const response=await fetch(`/api/portal/${token}/csat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,comment})});const payload=await response.json().catch(()=>({}));if(!response.ok)return setCsatError(payload.message||'Unable to submit feedback.');setCsat(payload.csat);};
  return <main className="portal-page"><section className="portal-ticket-card"><header className="portal-ticket-header"><div><span className="eyebrow">{ticket.key}</span><h1>{ticket.subject}</h1><p>{ticket.requesterEmail}</p></div><span className={`status-pill status-${ticket.status}`}>{ticket.status}</span></header><div className="portal-thread">{ticket.messages.map((message)=><article key={message.id} className={`portal-message ${message.authorType==='customer'?'mine':''}`}><div><strong>{message.authorType==='customer'?'You':message.authorName||'Support'}</strong><time>{formatDate(message.createdAt)}</time></div><p>{message.body}</p></article>)}</div>{csat?.eligible?<section className="portal-csat"><h3>How was your support experience?</h3>{csat.submitted?<p className="csat-recorded">Thanks for your feedback · {csat.rating}/5 {LABELS[csat.rating]}</p>:<><div className="portal-csat-ratings">{[1,2,3,4,5].map((value)=><button className={rating===value?'selected':''} key={value} onClick={()=>setRating(value)}>{value}</button>)}</div><textarea rows={3} maxLength={2000} value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Optional comment…"/>{csatError?<div className="form-error">{csatError}</div>:null}<button className="secondary-button" disabled={!rating} onClick={submitCsat}>Submit feedback</button></>}</section>:null}<div className="portal-composer"><h3>Reply to support</h3><textarea rows={5} value={reply} onChange={(e)=>setReply(e.target.value)} placeholder="Add more information…"/>{error?<div className="form-error">{error}</div>:null}<button className="primary-button" onClick={send} disabled={!reply.trim()}>Send reply</button></div></section></main>;
}
export async function getServerSideProps({params}){const {getPortalTicket}=require('../../lib/repository');const {getCsatForPortalToken}=require('../../lib/csat-repository');try{const ticket=await getPortalTicket(params.token);if(!ticket)return{notFound:true};let csat={eligible:false,submitted:false};try{csat=await getCsatForPortalToken(params.token);}catch(error){if(error?.code!=='42P01')console.error('Portal CSAT load failed:',error);}return{props:JSON.parse(JSON.stringify({initialTicket:ticket,initialCsat:csat,token:params.token}))};}catch(error){console.error(error);return{notFound:true};}}
