import { useState } from 'react';
const formatDate = (value) => new Date(value).toLocaleString();
export default function PortalTicket({ initialTicket, token }) {
  const [ticket, setTicket] = useState(initialTicket); const [reply, setReply] = useState(''); const [error, setError] = useState('');
  const refresh = async () => { const response = await fetch(`/api/portal/${token}`); if (response.ok) setTicket((await response.json()).ticket); };
  const send = async () => { if (!reply.trim()) return; const response = await fetch(`/api/portal/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ body: reply }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) return setError(payload.message || 'Unable to send reply.'); setReply(''); setError(''); await refresh(); };
  return <main className="portal-page"><section className="portal-ticket-card"><header className="portal-ticket-header"><div><span className="eyebrow">{ticket.key}</span><h1>{ticket.subject}</h1><p>{ticket.requesterEmail}</p></div><span className={`status-pill status-${ticket.status}`}>{ticket.status}</span></header><div className="portal-thread">{ticket.messages.map((message) => <article key={message.id} className={`portal-message ${message.authorType === 'customer' ? 'mine' : ''}`}><div><strong>{message.authorType === 'customer' ? 'You' : message.authorName || 'Support'}</strong><time>{formatDate(message.createdAt)}</time></div><p>{message.body}</p></article>)}</div><div className="portal-composer"><h3>Reply to support</h3><textarea rows={5} value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Add more information…"/>{error ? <div className="form-error">{error}</div> : null}<button className="primary-button" onClick={send} disabled={!reply.trim()}>Send reply</button></div></section></main>;
}
export async function getServerSideProps({ params }) { const { getPortalTicket } = require('../../lib/repository'); try { const ticket = await getPortalTicket(params.token); if (!ticket) return { notFound: true }; return { props: JSON.parse(JSON.stringify({ initialTicket: ticket, token: params.token })) }; } catch (error) { console.error(error); return { notFound: true }; } }
