import { useState } from 'react';

const LABELS={1:'Very dissatisfied',2:'Dissatisfied',3:'Neutral',4:'Satisfied',5:'Very satisfied'};
export default function SatisfactionPage({initialSurvey,token}){
  const [survey,setSurvey]=useState(initialSurvey);const [rating,setRating]=useState(initialSurvey.rating||0);const [comment,setComment]=useState(initialSurvey.comment||'');const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const submit=async()=>{if(!rating)return;setSaving(true);setError('');const response=await fetch(`/api/csat/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,comment})});const payload=await response.json().catch(()=>({}));setSaving(false);if(!response.ok)return setError(payload.message||'Unable to submit rating.');setSurvey({...survey,...payload.survey,submittedAt:payload.survey.submittedAt||new Date().toISOString()});};
  return <main className="csat-page"><section className="csat-card"><span className="eyebrow">{survey.organizationName} · {survey.key}</span><h1>How was your support experience?</h1><p className="csat-subject">{survey.subject}</p>{survey.submittedAt?<div className="csat-thanks"><div>✓</div><h2>Thank you</h2><p>Your feedback has been recorded.</p><strong>{survey.rating}/5 · {LABELS[survey.rating]}</strong></div>:<><div className="csat-ratings">{[1,2,3,4,5].map((value)=><button key={value} className={rating===value?'selected':''} onClick={()=>setRating(value)}><b>{value}</b><span>{LABELS[value]}</span></button>)}</div><label className="csat-comment"><span>Anything else you'd like us to know? <small>Optional</small></span><textarea rows={5} maxLength={2000} value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Tell us what went well or what we can improve…"/></label>{error?<div className="form-error">{error}</div>:null}<button className="primary-button csat-submit" disabled={!rating||saving} onClick={submit}>{saving?'Submitting…':'Submit feedback'}</button></>}</section></main>;
}
export async function getServerSideProps({params}){const {getCsatByToken}=require('../../lib/csat-repository');try{const survey=await getCsatByToken(params.token);if(!survey)return{notFound:true};return{props:JSON.parse(JSON.stringify({initialSurvey:survey,token:params.token}))};}catch(error){console.error(error);return{notFound:true};}}
