import { useState } from 'react';
import AppShell from '../components/AppShell';

const formatMinutes=(value)=>{const minutes=Number(value)||0;if(minutes<60)return`${minutes.toFixed(minutes%1?1:0)}m`;const hours=minutes/60;if(hours<24)return`${hours.toFixed(hours<10?1:0)}h`;return`${(hours/24).toFixed(1)}d`;};
const maxCount=(rows=[])=>Math.max(1,...rows.map((row)=>Number(row.count)||0));
function Breakdown({title,rows}){const max=maxCount(rows);return <section className="analytics-panel"><h2>{title}</h2>{rows.length?<div className="analytics-breakdown">{rows.map((row)=><div className="analytics-breakdown-row" key={row.label}><div><span>{row.label}</span><b>{row.count}</b></div><div className="analytics-track"><i style={{width:`${Math.max(3,(row.count/max)*100)}%`}}/></div></div>)}</div>:<div className="analytics-empty">No data in this period.</div>}</section>;}
export default function Analytics({session,initialAnalytics,dataError}){
  const [analytics,setAnalytics]=useState(initialAnalytics);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const changeWindow=async(days)=>{setLoading(true);setError('');try{const response=await fetch(`/api/analytics/overview?days=${days}`);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||'Unable to load analytics.');setAnalytics(payload.analytics);}catch(e){setError(e.message);}finally{setLoading(false);}};
  const k=analytics.kpis||{};const trendMax=Math.max(1,...(analytics.daily||[]).flatMap((row)=>[row.created,row.resolved]));
  return <AppShell session={session}><section className="workspace-card analytics-workspace"><header className="workspace-header"><div><span className="eyebrow">Support intelligence</span><h1>Analytics</h1><p>Operational health, SLA performance and customer satisfaction for {analytics.period.startDate} – {analytics.period.endDate}.</p></div><div className="analytics-window">{[7,30,90].map((days)=><button key={days} disabled={loading} className={analytics.days===days?'active':''} onClick={()=>changeWindow(days)}>{days}d</button>)}</div></header>{dataError?<div className="config-banner">{dataError}</div>:null}{error?<div className="config-banner">{error}</div>:null}<div className="analytics-kpis"><article><span>Created</span><strong>{k.created||0}</strong><small>tickets in window</small></article><article><span>Resolved</span><strong>{k.resolved||0}</strong><small>tickets in window</small></article><article><span>Backlog</span><strong>{k.backlog||0}</strong><small>new + open + pending</small></article><article><span>First-response SLA</span><strong>{k.firstResponseSlaPercent||0}%</strong><small>completed responses</small></article><article><span>Resolution SLA</span><strong>{k.resolutionSlaPercent||0}%</strong><small>resolved tickets</small></article><article><span>Median response</span><strong>{formatMinutes(k.medianFirstResponseMinutes)}</strong><small>created → first reply</small></article><article><span>Median resolution</span><strong>{formatMinutes(k.medianResolutionMinutes)}</strong><small>created → resolved</small></article><article><span>CSAT</span><strong>{k.csatAverage?`${k.csatAverage}/5`:'—'}</strong><small>{k.csatResponses||0} responses · {k.csatSatisfiedPercent||0}% satisfied</small></article></div><section className="analytics-panel analytics-trend-panel"><div className="analytics-panel-heading"><div><h2>Ticket flow</h2><p>Created versus resolved by UTC day.</p></div><div className="analytics-legend"><span><i className="created"/>Created</span><span><i className="resolved"/>Resolved</span></div></div><div className="analytics-trend">{(analytics.daily||[]).map((row)=><div className="analytics-day" key={row.date} title={`${row.date}: ${row.created} created, ${row.resolved} resolved`}><div className="analytics-bars"><i className="created" style={{height:`${Math.max(row.created?5:0,(row.created/trendMax)*100)}%`}}/><i className="resolved" style={{height:`${Math.max(row.resolved?5:0,(row.resolved/trendMax)*100)}%`}}/></div><small>{analytics.days<=7?row.date.slice(5):row.date.slice(8)}</small></div>)}</div></section><div className="analytics-grid"><Breakdown title="By status" rows={analytics.byStatus||[]}/><Breakdown title="By channel" rows={analytics.byChannel||[]}/><Breakdown title="By priority" rows={analytics.byPriority||[]}/><Breakdown title="Backlog by team" rows={analytics.byTeam||[]}/><Breakdown title="Backlog by agent" rows={analytics.byAgent||[]}/></div></section></AppShell>;
}
export async function getServerSideProps({req}){const {getSessionFromRequest}=require('../lib/auth');const {getSupportAnalytics}=require('../lib/analytics-repository');const session=getSessionFromRequest(req);if(!session)return{redirect:{destination:'/login',permanent:false}};try{return{props:JSON.parse(JSON.stringify({session,initialAnalytics:await getSupportAnalytics({organizationId:session.organizationId,days:30}),dataError:''}))};}catch(error){console.error(error);return{props:JSON.parse(JSON.stringify({session,initialAnalytics:{days:30,period:{startDate:'',endDate:''},kpis:{},daily:[],byStatus:[],byChannel:[],byPriority:[],byTeam:[],byAgent:[]},dataError:'Analytics is unavailable until the support database migration is applied.'}))};}}
