import { useMemo, useState } from 'react';
import AppShell from '../components/AppShell';
import TicketList from '../components/TicketList';
import TicketDetail from '../components/TicketDetail';
export async function getServerSideProps({ req, query }) {
  const { getSessionFromRequest } = require('../lib/auth'); const { listTickets } = require('../lib/repository'); const session = getSessionFromRequest(req);
  if (!session) return { redirect: { destination: '/login', permanent: false } };
  try { const tickets = await listTickets(session.organizationId); return { props: JSON.parse(JSON.stringify({ session, tickets, dataError: '', initialFilter: String(query.status || 'all') })) }; }
  catch (error) { console.error('Inbox load failed:', error); return { props: JSON.parse(JSON.stringify({ session, tickets: [], dataError: 'Database is not ready. Run npm run db:migrate after configuring DATABASE_URL.', initialFilter: String(query.status || 'all') })) }; }
}
export default function Inbox({ session, tickets: initialTickets, dataError, initialFilter }) {
  const [tickets, setTickets] = useState(initialTickets); const [selected, setSelected] = useState(null); const [filter, setFilter] = useState(['all','new','open','pending','resolved'].includes(initialFilter) ? initialFilter : 'all'); const [search, setSearch] = useState('');
  const visible = useMemo(() => tickets.filter((ticket) => (filter === 'all' || ticket.status === filter) && (!search || `${ticket.subject} ${ticket.requesterName} ${ticket.requesterEmail} ${ticket.key}`.toLowerCase().includes(search.toLowerCase()))), [tickets, filter, search]);
  const loadTicket = async (ticketOrId) => { const id = typeof ticketOrId === 'string' ? ticketOrId : ticketOrId.id; const response = await fetch(`/api/tickets/${id}`); if (!response.ok) return; const payload = await response.json(); setSelected(payload.ticket); const listResponse = await fetch('/api/tickets'); if (listResponse.ok) setTickets((await listResponse.json()).tickets); };
  return <AppShell session={session}><section className="workspace-card"><header className="workspace-header"><div><span className="eyebrow">Support workspace</span><h1>Inbox</h1></div><div className="header-actions"><label className="search-box"><span>⌕</span><input aria-label="Search tickets" placeholder="Search tickets" value={search} onChange={(e) => setSearch(e.target.value)}/></label><a className="secondary-button" href={`/request/${session.organizationSlug || ''}`} target="_blank" rel="noreferrer">New request ↗</a></div></header>{dataError ? <div className="config-banner">{dataError}</div> : null}<div className="queue-tabs"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>All <b>{tickets.length}</b></button><button className={filter === 'new' ? 'active' : ''} onClick={() => setFilter('new')}>New <b>{tickets.filter(t => t.status === 'new').length}</b></button><button className={filter === 'open' ? 'active' : ''} onClick={() => setFilter('open')}>Open <b>{tickets.filter(t => t.status === 'open').length}</b></button><button className={filter === 'pending' ? 'active' : ''} onClick={() => setFilter('pending')}>Pending <b>{tickets.filter(t => t.status === 'pending').length}</b></button></div><div className="inbox-grid"><section className="queue-panel"><div className="queue-heading"><strong>{filter === 'all' ? 'All conversations' : `${filter[0].toUpperCase()}${filter.slice(1)}`}</strong><span>{visible.length}</span></div><TicketList tickets={visible} selectedId={selected?.id} onSelect={loadTicket}/></section><TicketDetail ticket={selected} onRefresh={loadTicket} onClose={() => setSelected(null)}/></div></section></AppShell>;
}
