const crypto = require('crypto');
const cookie = require('cookie');
const { createSession } = require('../../../../lib/auth');
const { upsertOrganization } = require('../../../../lib/repository');
const { ACCOUNT_OAUTH_NONCE_COOKIE, ACCOUNT_OAUTH_RETURN_COOKIE, ACCOUNT_OAUTH_STATE_COOKIE, ACCOUNT_OAUTH_VERIFIER_COOKIE, exchangeAuthorizationCode, fetchAccountUserInfo, getAccountOAuthConfig, normalizeReturnPath } = require('../../../../lib/outborn/user-oauth');
const append = (res, value) => { const existing = res.getHeader('Set-Cookie'); res.setHeader('Set-Cookie', existing ? [...(Array.isArray(existing) ? existing : [existing]), value] : value); };
const equal = (a,b) => { if (!a || !b) return false; const aa=Buffer.from(String(a)); const bb=Buffer.from(String(b)); return aa.length===bb.length && crypto.timingSafeEqual(aa,bb); };
const clear = (res) => { const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:0,path:'/'}; [ACCOUNT_OAUTH_STATE_COOKIE,ACCOUNT_OAUTH_NONCE_COOKIE,ACCOUNT_OAUTH_VERIFIER_COOKIE,ACCOUNT_OAUTH_RETURN_COOKIE].forEach(name=>append(res,cookie.serialize(name,'',options))); };
const orgFromUserInfo = (userinfo) => { const candidate=(Array.isArray(userinfo.organizations)?userinfo.organizations:[])[0] || userinfo.organization || {}; const id=String(candidate.organizationId || candidate.id || userinfo.organization_id || '').trim(); if (!id) return null; return { id, slug:String(candidate.slug || candidate.organizationSlug || id).trim(), name:String(candidate.name || candidate.organizationName || candidate.slug || 'Organization').trim() }; };
export default async function handler(req,res){
  if(req.method!=='GET') return res.status(405).json({success:false,message:'Method not allowed'});
  const cookies=cookie.parse(req.headers.cookie||''); const code=String(req.query.code||'').trim(); const state=String(req.query.state||'').trim(); const savedState=cookies[ACCOUNT_OAUTH_STATE_COOKIE]||''; const verifier=cookies[ACCOUNT_OAUTH_VERIFIER_COOKIE]||''; const returnTo=normalizeReturnPath(cookies[ACCOUNT_OAUTH_RETURN_COOKIE]);
  if(req.query.error){clear(res);return res.redirect(302,`/login?accountError=${encodeURIComponent(req.query.error)}`);} if(!code||!verifier||!equal(savedState,state)){clear(res);return res.redirect(302,'/login?accountError=invalid_oauth_state');}
  try{const config=getAccountOAuthConfig(req);const tokens=await exchangeAuthorizationCode({accountBaseUrl:config.accountBaseUrl,clientId:config.clientId,redirectUri:config.redirectUri,code,verifier});const userinfo=await fetchAccountUserInfo({accountBaseUrl:config.accountBaseUrl,accessToken:tokens.access_token});const org=orgFromUserInfo(userinfo);if(!org) throw new Error('No Outborn organization membership is available for Obsi Support.');await upsertOrganization(org);clear(res);createSession(res,{sub:String(userinfo.sub),email:String(userinfo.email),name:String(userinfo.name||userinfo.preferred_username||userinfo.email),organizationId:org.id,organizationSlug:org.slug,organizationName:org.name},Math.max(300,Math.min(Number(tokens.expires_in)||3600,3600)));return res.redirect(302,returnTo);}catch(error){console.error('Outborn Account callback failed:',error);clear(res);return res.redirect(302,'/login?accountError=account_auth_failed');}
}
